[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
cmds = [
  "cd ../.. && npm install",
  "cd apps/web && npm install"
]

[phases.build]
cmds = [
  "cd apps/web && npm run build"
]

[start]
cmd = "cd apps/web && npm run start"

